/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.livraria.view;

/**
 *
 * @author Gnunes
 */
public class TelaLoginView extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginView
     */
    // Atributo para alternar entre telas temporarias
    private javax.swing.JFrame telaAnterior;

    public TelaLoginView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public TelaLoginView(javax.swing.JFrame telaAnterior) {
        initComponents();
        this.telaAnterior = telaAnterior;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLoginGrid = new javax.swing.JPanel();
        labelLoginGrid = new javax.swing.JLabel();
        buttonNewLogin = new javax.swing.JButton();
        buttonRegistrar = new javax.swing.JButton();
        panelDireitoCards = new javax.swing.JPanel();
        panelRegistrar = new javax.swing.JPanel();
        labelLogo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        panelLogin = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        labelUser1 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        buttonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLoginGrid.setBackground(new java.awt.Color(0, 0, 0));
        panelLoginGrid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLoginGrid.setBackground(new java.awt.Color(204, 204, 255));
        labelLoginGrid.setForeground(new java.awt.Color(204, 204, 255));
        labelLoginGrid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo HD.png"))); // NOI18N
        panelLoginGrid.add(labelLoginGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 150));

        buttonNewLogin.setBackground(new java.awt.Color(204, 204, 204));
        buttonNewLogin.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonNewLogin.setText("Login");
        buttonNewLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonNewLogin.setOpaque(true);
        buttonNewLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewLoginActionPerformed(evt);
            }
        });
        panelLoginGrid.add(buttonNewLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 110, -1));

        buttonRegistrar.setBackground(new java.awt.Color(204, 204, 204));
        buttonRegistrar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonRegistrar.setText("Registrar");
        buttonRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonRegistrar.setOpaque(true);
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });
        panelLoginGrid.add(buttonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 110, -1));

        getContentPane().add(panelLoginGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 600));

        panelDireitoCards.setLayout(new java.awt.CardLayout());

        panelRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_HD_-_text-removebg-preview.png"))); // NOI18N
        labelLogo1.setPreferredSize(new java.awt.Dimension(550, 100));
        panelRegistrar.add(labelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 550, 150));

        jLabel1.setText("Nome: ");
        panelRegistrar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jTextField1.setText("jTextField1");
        panelRegistrar.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 460, -1));

        jLabel2.setText("Email: ");
        panelRegistrar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jTextField2.setText("jTextField2");
        panelRegistrar.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 460, -1));

        jLabel3.setText("Senha: ");
        panelRegistrar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jPasswordField1.setText("jPasswordField1");
        panelRegistrar.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 210, -1));

        jLabel4.setText("Confirmar: ");
        panelRegistrar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        jPasswordField2.setText("jPasswordField2");
        panelRegistrar.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 220, -1));

        panelDireitoCards.add(panelRegistrar, "card3");

        panelLogin.setBackground(new java.awt.Color(51, 51, 51));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_HD_-_text-removebg-preview.png"))); // NOI18N
        labelLogo.setPreferredSize(new java.awt.Dimension(550, 100));
        panelLogin.add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 550, 150));

        labelUser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelUser.setText("Usuario:");
        labelUser.setOpaque(true);
        panelLogin.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));
        panelLogin.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 330, -1));

        labelUser1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelUser1.setText("Senha: ");
        labelUser1.setOpaque(true);
        panelLogin.add(labelUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 50, -1));

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        panelLogin.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 330, -1));

        buttonOK.setBackground(new java.awt.Color(204, 204, 204));
        buttonOK.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonOK.setText("Ok");
        buttonOK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonOK.setOpaque(true);
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });
        panelLogin.add(buttonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 50, -1));

        panelDireitoCards.add(panelLogin, "card2");

        getContentPane().add(panelDireitoCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 550, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNewLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNewLoginActionPerformed

    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRegistrarActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed
    
    // Botão OK
    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        String usuario = txtUser.getText();
        String senha = new String(txtSenha.getPassword());

        String avisoMensagem = "";
        String avisoTitulo = "";
        int tipoMensagem = javax.swing.JOptionPane.ERROR_MESSAGE;

        if (usuario.isEmpty() || senha.isEmpty()) {
            avisoMensagem = "Por favor, preencha todos os campos!";
            avisoTitulo = "Campos Vazios";
            tipoMensagem = javax.swing.JOptionPane.WARNING_MESSAGE;

        } else if (!usuario.equals("user") || !senha.equals("123")) {
            avisoMensagem = "Usuário ou senha incorretos!";
            avisoTitulo = "Erro de Autenticação";
            tipoMensagem = javax.swing.JOptionPane.ERROR_MESSAGE;
        }

        if (!avisoMensagem.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    avisoMensagem,
                    avisoTitulo,
                    tipoMensagem);
        } else {
            if (this.telaAnterior == null) {
                TelaInicialView inicial = new TelaInicialView();
                inicial.setVisible(true);
                this.dispose();
            } else {
                telaAnterior.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_buttonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaLoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNewLogin;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelLoginGrid;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelLogo1;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelUser1;
    private javax.swing.JPanel panelDireitoCards;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelLoginGrid;
    private javax.swing.JPanel panelRegistrar;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
