/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.livraria.view;

import com.mycompany.livraria.controller.LivroController;
import com.mycompany.livraria.controller.PessoaController;
import com.mycompany.livraria.model.*;
import java.util.*;

/**
 *
 * @author Gnunes
 */
public class TelaAdmView extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAdmView.class.getName());
    
    //instanciando controladores
     private final PessoaController pessoaController = new PessoaController();
     private final LivroController livroController = new LivroController();
    /**
     * Creates new form TelaAdmView
     *
     */
    public TelaAdmView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogo = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        panelOpcoes = new javax.swing.JPanel();
        buttonCatalogo = new javax.swing.JButton();
        buttonDelCliente = new javax.swing.JButton();
        buttonAddLivro = new javax.swing.JButton();
        buttonDelLivro = new javax.swing.JButton();
        buttonListaCliente = new javax.swing.JButton();
        panelCards = new javax.swing.JPanel();
        cardCatalogo = new javax.swing.JPanel();
        scrollCatalogo = new javax.swing.JScrollPane();
        tableCatalogo = new javax.swing.JTable();
        cardAddLivro = new javax.swing.JPanel();
        labelUser = new javax.swing.JLabel();
        labelUser1 = new javax.swing.JLabel();
        labelUser2 = new javax.swing.JLabel();
        labelUser3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        labelUser4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        buttonCadastrarLivro = new javax.swing.JButton();
        cBoxCategoria = new javax.swing.JComboBox<>();
        cardDelLivro = new javax.swing.JPanel();
        buttonBuscar = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        labelCodLivro = new javax.swing.JLabel();
        buttonDeletar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaInfo = new javax.swing.JTextArea();
        cardListaClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoADM.png"))); // NOI18N
        panelLogo.add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        getContentPane().add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        panelOpcoes.setBackground(new java.awt.Color(0, 0, 0));
        panelOpcoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCatalogo.setBackground(new java.awt.Color(204, 204, 204));
        buttonCatalogo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonCatalogo.setText("Catálogo");
        buttonCatalogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonCatalogo.setOpaque(true);
        buttonCatalogo.addActionListener(this::buttonCatalogoActionPerformed);
        panelOpcoes.add(buttonCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, -1));

        buttonDelCliente.setBackground(new java.awt.Color(204, 204, 204));
        buttonDelCliente.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonDelCliente.setText("Del Cliente");
        buttonDelCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonDelCliente.setOpaque(true);
        buttonDelCliente.addActionListener(this::buttonDelClienteActionPerformed);
        panelOpcoes.add(buttonDelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 110, -1));

        buttonAddLivro.setBackground(new java.awt.Color(204, 204, 204));
        buttonAddLivro.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonAddLivro.setText("Add Livro");
        buttonAddLivro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonAddLivro.setOpaque(true);
        buttonAddLivro.addActionListener(this::buttonAddLivroActionPerformed);
        panelOpcoes.add(buttonAddLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, -1));

        buttonDelLivro.setBackground(new java.awt.Color(204, 204, 204));
        buttonDelLivro.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonDelLivro.setText("Del Livro");
        buttonDelLivro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonDelLivro.setOpaque(true);
        buttonDelLivro.addActionListener(this::buttonDelLivroActionPerformed);
        panelOpcoes.add(buttonDelLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, -1));

        buttonListaCliente.setBackground(new java.awt.Color(204, 204, 204));
        buttonListaCliente.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonListaCliente.setText("Lista Clientes");
        buttonListaCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonListaCliente.setOpaque(true);
        buttonListaCliente.addActionListener(this::buttonListaClienteActionPerformed);
        panelOpcoes.add(buttonListaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, -1));

        getContentPane().add(panelOpcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 500));

        panelCards.setLayout(new java.awt.CardLayout());

        cardCatalogo.setLayout(new java.awt.BorderLayout());

        tableCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Autor", "Categoria", "Preço", "Codigo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollCatalogo.setViewportView(tableCatalogo);

        cardCatalogo.add(scrollCatalogo, java.awt.BorderLayout.CENTER);

        panelCards.add(cardCatalogo, "cardCatalogo");

        cardAddLivro.setBackground(new java.awt.Color(153, 153, 153));
        cardAddLivro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelUser.setText("Titulo:");
        labelUser.setOpaque(true);
        cardAddLivro.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        labelUser1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelUser1.setText("Preço:");
        labelUser1.setOpaque(true);
        cardAddLivro.add(labelUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        labelUser2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelUser2.setText("Autor:");
        labelUser2.setOpaque(true);
        cardAddLivro.add(labelUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        labelUser3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelUser3.setText("Codigo:");
        labelUser3.setOpaque(true);
        cardAddLivro.add(labelUser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));
        cardAddLivro.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 200, -1));

        labelUser4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelUser4.setText("Categoria:");
        labelUser4.setOpaque(true);
        cardAddLivro.add(labelUser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        txtTitulo.addActionListener(this::txtTituloActionPerformed);
        cardAddLivro.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 510, -1));
        cardAddLivro.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 510, -1));

        txtPreco.addActionListener(this::txtPrecoActionPerformed);
        cardAddLivro.add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 200, -1));

        buttonCadastrarLivro.setBackground(new java.awt.Color(204, 204, 204));
        buttonCadastrarLivro.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonCadastrarLivro.setText("Adicionar");
        buttonCadastrarLivro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonCadastrarLivro.setOpaque(true);
        buttonCadastrarLivro.addActionListener(this::buttonCadastrarLivroActionPerformed);
        cardAddLivro.add(buttonCadastrarLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 90, -1));

        cBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione uma Categoria --", "Ficção Científica", "Romance", "Suspense", "Fantasia", "Terror", "Biografia", "Autoajuda", "História" }));
        cardAddLivro.add(cBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 200, -1));

        panelCards.add(cardAddLivro, "cardAddLivro");

        cardDelLivro.setBackground(new java.awt.Color(153, 153, 153));
        cardDelLivro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonBuscar.setBackground(new java.awt.Color(204, 204, 204));
        buttonBuscar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonBuscar.setText("Buscar");
        buttonBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonBuscar.setOpaque(true);
        buttonBuscar.addActionListener(this::buttonBuscarActionPerformed);
        cardDelLivro.add(buttonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 80, 20));
        cardDelLivro.add(txtBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 250, -1));

        labelCodLivro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelCodLivro.setText("Codigo do Livro:");
        labelCodLivro.setOpaque(true);
        cardDelLivro.add(labelCodLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        buttonDeletar.setBackground(new java.awt.Color(204, 204, 204));
        buttonDeletar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonDeletar.setText("Deletar");
        buttonDeletar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonDeletar.setEnabled(false);
        buttonDeletar.setOpaque(true);
        buttonDeletar.addActionListener(this::buttonDeletarActionPerformed);
        cardDelLivro.add(buttonDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 80, 20));

        txtAreaInfo.setColumns(20);
        txtAreaInfo.setRows(5);
        jScrollPane2.setViewportView(txtAreaInfo);

        cardDelLivro.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 540, 190));

        panelCards.add(cardDelLivro, "cardDelLivro");

        cardListaClientes.setLayout(new java.awt.BorderLayout());

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Email", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableClientes);

        cardListaClientes.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelCards.add(cardListaClientes, "cardListaClientes");
        cardListaClientes.getAccessibleContext().setAccessibleParent(panelCards);

        getContentPane().add(panelCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 650, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDelClienteActionPerformed

    private void buttonDelLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelLivroActionPerformed
        mudarTela("cardDelLivro");
    }//GEN-LAST:event_buttonDelLivroActionPerformed

    private void buttonListaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListaClienteActionPerformed
        mudarTela("cardListaClientes");
        
        //Chama o controller para listar os clientes
        List<Pessoa> pessoas;
        try {
            pessoas = pessoaController.list();

            //Se não houver erros lista os clientes
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tableClientes.getModel();
            modelo.setNumRows(0);

            for (Pessoa p : pessoas) {
                modelo.addRow(new Object[]{
                    p.getNome(),
                    p.getEmail(),
                    p.getIdUsuario()
                });
            }

        } catch (RuntimeException e) {
            //Se houver erro exibe mensgaem de erro 
            mensagem("aviso", e.getMessage());
            //E apaga a caixa de texto
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tableClientes.getModel();
            modelo.setNumRows(0);
        }

        /*
        PessoaDao dao = new PessoaDao();
        List<Pessoa> pessoas = dao.listarTodos();

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tableClientes.getModel();
        modelo.setNumRows(0);

        for (Pessoa p : pessoas) {
            modelo.addRow(new Object[]{
                p.getNome(),
                p.getEmail(),
                p.getIdUsuario()
            });
        }
         */

    }//GEN-LAST:event_buttonListaClienteActionPerformed

    private void buttonCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCatalogoActionPerformed

        mudarTela("cardCatalogo");
        List<Livro> livros = new ArrayList<>();
        
        //Instancia Controller na função
        LivroController livroController = new LivroController();
        
        //Tenta trazer a lista de livros
        try {
            livros = livroController.list();
        } catch (RuntimeException e) {
            //Se não der certo, mensagem de erro
            mensagem("aviso", e.getMessage());
        }

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tableCatalogo.getModel();
        modelo.setNumRows(0);

        //lista os livros encontrados
        for (Livro l : livros) {
            modelo.addRow(new Object[]{
                l.getNome(),
                l.getAutor(),
                l.getCategoria(),
                "R$ " + String.format("%.2f", l.getPreco()),
                l.getCodigo()
            });
        }
    }//GEN-LAST:event_buttonCatalogoActionPerformed

    private void buttonAddLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddLivroActionPerformed
        mudarTela("cardAddLivro");
    }//GEN-LAST:event_buttonAddLivroActionPerformed

    private void buttonCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarLivroActionPerformed

        String titulo = txtTitulo.getText();
        String autor = txtAutor.getText();
        String tempPreco = txtPreco.getText();
        String codigo = txtCodigo.getText();
        String categoria = cBoxCategoria.getSelectedItem().toString();
        Livro livro = new Livro();

        //verificando argumentos inválidos
        if (titulo.trim().isEmpty() || autor.trim().isEmpty() || tempPreco.trim().isEmpty() || codigo.trim().isEmpty() || cBoxCategoria.getSelectedIndex() == 0) {
            mensagem("aviso", "Todos os campos devem ser preenchidos");
            return;
        }

        //transformando em valores válidos
        tempPreco = tempPreco.replace(",", ".");
        double preco = Double.parseDouble(tempPreco);

        //setando os valores de livro
        livro.setNome(titulo);
        livro.setAutor(autor);
        livro.setCategoria(categoria);
        livro.setPreco(preco);
        livro.setCodigo(codigo);

        try {

            livroController.register(livro);

            //Se o livro foi cadastrado com sucesso exibe a mensagem
            mensagem("sucesso", "Livro adicionado com sucesso!");

            txtTitulo.setText("");
            txtAutor.setText("");
            txtPreco.setText("");
            txtCodigo.setText("");
            cBoxCategoria.setSelectedIndex(0);
            txtTitulo.requestFocus();

        } catch (RuntimeException e) {
            mensagem("aviso", e.getMessage());
        }
    }//GEN-LAST:event_buttonCadastrarLivroActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        String codigoBusca = txtBusca.getText();
        Livro livro;

        //verificando se é a pessoa digitou alguma coisa
        if (codigoBusca.trim().isEmpty()) {
            mensagem("aviso", "O campo código não pode estar em branco");
            return;
        }

        //Manda para o controller procurar
        try {
            livro = livroController.search(codigoBusca);
        } catch (RuntimeException e) {
            //exibe a mensagem de erro
            mensagem("aviso", e.getMessage());
            //Reseta o campo de texto e desativa o botão de deletar
            txtAreaInfo.setText("");
            buttonDeletar.setEnabled(false);
            return;
        }

        //Mostrando as informações 
        String informacoes = "=== INFORMAÇÕES DO LIVRO ===\n\n"
                + "Título: " + livro.getNome() + "\n"
                + "Autor: " + livro.getAutor() + "\n"
                + "Categoria: " + livro.getCategoria() + "\n"
                + "Preço: R$ " + String.format("%.2f", livro.getPreco()) + "\n\n"
                + "Este é o livro que deseja excluir?";

        txtAreaInfo.setText(informacoes);

        buttonDeletar.setEnabled(true);
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletarActionPerformed

        String codigo = txtBusca.getText();

        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "ATENÇÃO: Tem certeza que deseja excluir permanentemente este livro do catálogo?",
                "Confirmar Exclusão",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        //Se a pessoa confirmar a exclusão ele tenta deletar
        if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
            try {
                livroController.delete(codigo);

                //Se der tudo acerto envia mesagem de confirmação
                mensagem("sucesso", "O livro foi excluído com sucesso!");

                txtBusca.setText("");
                txtAreaInfo.setText("");
                buttonDeletar.setEnabled(false);
                txtBusca.requestFocus();
            } catch (RuntimeException e) {
                //Se der algum erro envia a mensagem de erro
                mensagem("aviso", e.getMessage());
            }
        }
    }//GEN-LAST:event_buttonDeletarActionPerformed

    private void mudarTela(String nomeDoCard) {
        java.awt.CardLayout card = (java.awt.CardLayout) panelCards.getLayout();
        card.show(panelCards, nomeDoCard);

        panelCards.revalidate();
        panelCards.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAdmView().setVisible(true));
    }

    /**
     * Exibe pop-ups padronizados para o usuário.
     *
     * * @param tipo Pode ser: "sucesso", "erro", "aviso" ou "info"
     * @param mensagem O texto que vai aparecer na caixinha
     */
    private void mensagem(String tipo, String mensagem) {
        int tipoIcone;
        String titulo;

        switch (tipo.toLowerCase()) {
            case "erro":
                tipoIcone = javax.swing.JOptionPane.ERROR_MESSAGE;
                titulo = "Erro no Sistema";
                break;
            case "aviso":
                tipoIcone = javax.swing.JOptionPane.WARNING_MESSAGE;
                titulo = "Atenção";
                break;
            case "sucesso":
                tipoIcone = javax.swing.JOptionPane.INFORMATION_MESSAGE;
                titulo = "Sucesso";
                break;
            default:
                tipoIcone = javax.swing.JOptionPane.INFORMATION_MESSAGE;
                titulo = "Informação";
                break;
        }

        javax.swing.JOptionPane.showMessageDialog(this, mensagem, titulo, tipoIcone);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddLivro;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonCadastrarLivro;
    private javax.swing.JButton buttonCatalogo;
    private javax.swing.JButton buttonDelCliente;
    private javax.swing.JButton buttonDelLivro;
    private javax.swing.JButton buttonDeletar;
    private javax.swing.JButton buttonListaCliente;
    private javax.swing.JComboBox<String> cBoxCategoria;
    private javax.swing.JPanel cardAddLivro;
    private javax.swing.JPanel cardCatalogo;
    private javax.swing.JPanel cardDelLivro;
    private javax.swing.JPanel cardListaClientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCodLivro;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelUser1;
    private javax.swing.JLabel labelUser2;
    private javax.swing.JLabel labelUser3;
    private javax.swing.JLabel labelUser4;
    private javax.swing.JPanel panelCards;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelOpcoes;
    private javax.swing.JScrollPane scrollCatalogo;
    private javax.swing.JTable tableCatalogo;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTextArea txtAreaInfo;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
