/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.livraria.view;

import com.mycompany.livraria.controller.PessoaController;
import com.mycompany.livraria.model.Pessoa;
import com.mycompany.livraria.dao.PessoaDao;
/**
 *
 * @author br992
 */
public class TelaInfoView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInfoView.class.getName());
    
    
    //Controller
    PessoaController pessoaController = new PessoaController();
    
    private final Pessoa usuario;
    
    /**
     * Creates new form TelaInfoView
     * @param usuario usuario logado
     * @param telaInicial tela inicial view
     */
    public TelaInfoView(Pessoa usuario, TelaInicialView telaInicial) {
        initComponents();
        this.usuario = usuario;
        this.setLocationRelativeTo(null);
        
        preencherDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonExcluirConta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonExcluirConta.setText("jButton1");
        ButtonExcluirConta.addActionListener(this::ButtonExcluirContaActionPerformed);
        jPanel1.add(ButtonExcluirConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 61, -1));

        jLabel2.setText("jLabelTipoDeUsuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 61, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -1, 310, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExcluirContaActionPerformed
        int resposta = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja excluir sua conta? Esta ação não pode ser desfeita!", 
            "CONFIRMAR EXCLUSÃO", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.WARNING_MESSAGE
    );
        
        if(resposta == javax.swing.JOptionPane.YES_OPTION){
            try{
                //chama a controller para deletar aquele usuário com aquele id
                String txtId = String.valueOf(usuario.getIdUsuario());
                pessoaController.delete(txtId);
                
                //Se for excluído corretamente 
                javax.swing.JOptionPane.showMessageDialog(this, "Conta excluída com sucesso!");
                
                //Seta o usuário logado como nenhum em tela incial
                TelaInicialView telaInicial = new TelaInicialView();
                telaInicial.setVisible(true);
                
                //Fecha essa janela
                this.dispose();
                
            } catch(RuntimeException e){
                mensagem("aviso", e.getMessage());
            }
        }
    }//GEN-LAST:event_ButtonExcluirContaActionPerformed

    private void preencherDados(){
        lblNome.setText("Usuário: "+usuario.getNome());
        lblEmail.setText("E-mail: " + usuario.getEmail());
        lblSaldo.setText("Saldo Total: " + usuario.getSaldo());
        
        String tipoDaConta = usuario.isAdm() ? "Administrador" : "Usuário Comum";
        
        lblTipoConta.setText("Tipo: " + tipoDaConta);
    }
    
    
    
    private void mensagem(String tipo, String mensagem) {
        int tipoIcone;
        String titulo;

        switch (tipo.toLowerCase()) {
            case "erro":
                tipoIcone = javax.swing.JOptionPane.ERROR_MESSAGE;
                titulo = "Erro no Sistema";
                break;
            case "aviso":
                tipoIcone = javax.swing.JOptionPane.WARNING_MESSAGE;
                titulo = "Atenção";
                break;
            case "sucesso":
                tipoIcone = javax.swing.JOptionPane.INFORMATION_MESSAGE;
                titulo = "Sucesso";
                break;
            default:
                tipoIcone = javax.swing.JOptionPane.INFORMATION_MESSAGE;
                titulo = "Informação";
                break;
        }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInfoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonExcluirConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
