/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.livraria.view;

import com.mycompany.livraria.controller.PessoaController;
import com.mycompany.livraria.model.Pessoa;
import com.mycompany.livraria.dao.PessoaDao;

/**
 *
 * @author br992
 */
public class TelaInfoView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInfoView.class.getName());

    //Controller
    PessoaController pessoaController = new PessoaController();

    private final Pessoa usuario;

    /**
     * Creates new form TelaInfoView
     *
     * @param usuario usuario logado
     * @param telaInicial tela inicial view
     */
    public TelaInfoView(Pessoa usuario) {
        initComponents();
        this.usuario = usuario;
        this.setLocationRelativeTo(null);

        preencherDados();
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitle = new javax.swing.JPanel();
        labelTop = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        buttonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 500));
        setMinimumSize(new java.awt.Dimension(300, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitle.setBackground(new java.awt.Color(0, 0, 0));
        panelTitle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTop.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        labelTop.setForeground(new java.awt.Color(255, 255, 255));
        labelTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTop.setText("Info");
        panelTitle.add(labelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, -1));

        getContentPane().add(panelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setOpaque(false);
        jScrollPane1.setViewportView(txtArea);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 260, 280));

        buttonExcluir.setBackground(new java.awt.Color(204, 204, 204));
        buttonExcluir.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonExcluir.setText("Excluir Conta");
        buttonExcluir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonExcluir.setOpaque(true);
        buttonExcluir.addActionListener(this::buttonExcluirActionPerformed);
        jPanel3.add(buttonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 100, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        int resposta = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja excluir sua conta? Esta ação não pode ser desfeita!", 
            "CONFIRMAR EXCLUSÃO", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.WARNING_MESSAGE
    );
        
        if(resposta == javax.swing.JOptionPane.YES_OPTION){
            try{
                //chama a controller para deletar aquele usuário com aquele id
                String txtId = String.valueOf(usuario.getIdUsuario());
                pessoaController.delete(txtId);
                
                //Se for excluído corretamente 
                javax.swing.JOptionPane.showMessageDialog(this, "Conta excluída com sucesso!");
                
                //Seta o usuário logado como nenhum em tela incial
                TelaInicialView telaInicial = new TelaInicialView();
                telaInicial.setVisible(true);
                
                //Fecha essa janela
                this.dispose();
                
            } catch(RuntimeException e){
                mensagem("aviso", e.getMessage());
            }
        }
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void preencherDados() {

        String tipoDaConta = usuario.isAdm() ? "Administrador" : "Usuário Comum";

        String informacoesFormatadas = String.format(
                "Usuário: %s\n\nE-mail: %s\n\nSaldo Total: R$ %.2f\n\nTipo: %s",
                usuario.getNome(),
                usuario.getEmail(),
                usuario.getSaldo(),
                tipoDaConta
        );

        txtArea.setText(informacoesFormatadas);
    }

    private void mensagem(String tipo, String mensagem) {
        int tipoIcone;
        String titulo;

        switch (tipo.toLowerCase()) {
            case "erro":
                tipoIcone = javax.swing.JOptionPane.ERROR_MESSAGE;
                titulo = "Erro no Sistema";
                break;
            case "aviso":
                tipoIcone = javax.swing.JOptionPane.WARNING_MESSAGE;
                titulo = "Atenção";
                break;
            case "sucesso":
                tipoIcone = javax.swing.JOptionPane.INFORMATION_MESSAGE;
                titulo = "Sucesso";
                break;
            default:
                tipoIcone = javax.swing.JOptionPane.INFORMATION_MESSAGE;
                titulo = "Informação";
                break;
        }
    }
        /**
         * @param args the command line arguments
         */
       
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Pessoa pessoa = new Pessoa();
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInfoView(pessoa).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTop;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
