/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.livraria.view;

/**
 *
 * @author Gnunes
 */
public class TelaLoginView extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginView
     */
    // Atributo para alternar entre telas temporarias
    private javax.swing.JFrame telaAnterior;

    public TelaLoginView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public TelaLoginView(javax.swing.JFrame telaAnterior) {
        initComponents();
        this.telaAnterior = telaAnterior;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLoginGrid = new javax.swing.JPanel();
        labelLoginGrid = new javax.swing.JLabel();
        buttonNewLogin = new javax.swing.JButton();
        buttonRegistrar = new javax.swing.JButton();
        panelDireitoCards = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        labelUser1 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        buttonOK = new javax.swing.JButton();
        panelRegistrar = new javax.swing.JPanel();
        labelLogo1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNovaSenha = new javax.swing.JPasswordField();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        labelConfirmar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLoginGrid.setBackground(new java.awt.Color(0, 0, 0));
        panelLoginGrid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLoginGrid.setBackground(new java.awt.Color(204, 204, 255));
        labelLoginGrid.setForeground(new java.awt.Color(204, 204, 255));
        labelLoginGrid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo HD.png"))); // NOI18N
        panelLoginGrid.add(labelLoginGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 150));

        buttonNewLogin.setBackground(new java.awt.Color(204, 204, 204));
        buttonNewLogin.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonNewLogin.setText("Login");
        buttonNewLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonNewLogin.setOpaque(true);
        buttonNewLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewLoginActionPerformed(evt);
            }
        });
        panelLoginGrid.add(buttonNewLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 110, -1));

        buttonRegistrar.setBackground(new java.awt.Color(204, 204, 204));
        buttonRegistrar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonRegistrar.setText("Registrar");
        buttonRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonRegistrar.setOpaque(true);
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });
        panelLoginGrid.add(buttonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 110, -1));

        getContentPane().add(panelLoginGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 600));

        panelDireitoCards.setLayout(new java.awt.CardLayout());

        panelLogin.setBackground(new java.awt.Color(51, 51, 51));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_HD_-_text-removebg-preview.png"))); // NOI18N
        labelLogo.setPreferredSize(new java.awt.Dimension(550, 100));
        panelLogin.add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 550, 150));

        labelUser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelUser.setText("Usuario:");
        labelUser.setOpaque(true);
        panelLogin.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));
        panelLogin.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 420, -1));

        labelUser1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelUser1.setText("Senha: ");
        labelUser1.setOpaque(true);
        panelLogin.add(labelUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 50, -1));

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        panelLogin.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 420, -1));

        buttonOK.setBackground(new java.awt.Color(204, 204, 204));
        buttonOK.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonOK.setText("Entrar");
        buttonOK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonOK.setOpaque(true);
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });
        panelLogin.add(buttonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 80, -1));

        panelDireitoCards.add(panelLogin, "panelLogin");

        panelRegistrar.setBackground(new java.awt.Color(51, 51, 51));
        panelRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_HD_-_text-removebg-preview.png"))); // NOI18N
        labelLogo1.setPreferredSize(new java.awt.Dimension(550, 100));
        panelRegistrar.add(labelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 550, 150));
        panelRegistrar.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 460, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        panelRegistrar.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 460, -1));

        txtNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovaSenhaActionPerformed(evt);
            }
        });
        panelRegistrar.add(txtNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 210, -1));
        panelRegistrar.add(txtConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 220, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 204, 0), null, null));
        panelRegistrar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 110, -1));

        labelNome.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelNome.setText("Nome:");
        labelNome.setOpaque(true);
        panelRegistrar.add(labelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        labelEmail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelEmail.setText("Email:");
        labelEmail.setOpaque(true);
        panelRegistrar.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        labelSenha.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelSenha.setText("Senha:");
        labelSenha.setOpaque(true);
        panelRegistrar.add(labelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        labelConfirmar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelConfirmar.setText("Confirmar:");
        labelConfirmar.setOpaque(true);
        panelRegistrar.add(labelConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        panelDireitoCards.add(panelRegistrar, "panelRegistrar");

        getContentPane().add(panelDireitoCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 550, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNewLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewLoginActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout) panelDireitoCards.getLayout();

        card.show(panelDireitoCards, "panelLogin");
        panelDireitoCards.revalidate();
        panelDireitoCards.repaint();
    }//GEN-LAST:event_buttonNewLoginActionPerformed

    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout) panelDireitoCards.getLayout();

        card.show(panelDireitoCards, "panelRegistrar");
        panelDireitoCards.revalidate();
        panelDireitoCards.repaint();
    }//GEN-LAST:event_buttonRegistrarActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    // Botão OK
    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        String usuario = txtUser.getText();
        String senha = new String(txtSenha.getPassword());

        String avisoMensagem = "";
        String avisoTitulo = "";
        int tipoMensagem = javax.swing.JOptionPane.ERROR_MESSAGE;

        if (usuario.isEmpty() || senha.isEmpty()) {
            avisoMensagem = "Por favor, preencha todos os campos!";
            avisoTitulo = "Campos Vazios";
            tipoMensagem = javax.swing.JOptionPane.WARNING_MESSAGE;

        } else if (!usuario.equals("user") || !senha.equals("123")) {
            avisoMensagem = "Usuário ou senha incorretos!";
            avisoTitulo = "Erro de Autenticação";
            tipoMensagem = javax.swing.JOptionPane.ERROR_MESSAGE;
        }

        if (!avisoMensagem.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    avisoMensagem,
                    avisoTitulo,
                    tipoMensagem);
        } else {
            if (this.telaAnterior == null) {
                TelaInicialView inicial = new TelaInicialView();
                inicial.setVisible(true);
                this.dispose();
            } else {
                telaAnterior.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_buttonOKActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovaSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaLoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNewLogin;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelConfirmar;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelLoginGrid;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelLogo1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelUser1;
    private javax.swing.JPanel panelDireitoCards;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelLoginGrid;
    private javax.swing.JPanel panelRegistrar;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtNovaSenha;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
