/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.livraria.view;
import com.mycompany.livraria.dao.PessoaDao;
import com.mycompany.livraria.model.Pessoa;
import javax.swing.JOptionPane;

/**
 *
 * @author Gnunes
 */
  

    public class TelaInicialView extends javax.swing.JFrame {

        /**
         * Creates new form TelaInicialView
         */
        public TelaInicialView() {
            initComponents();
            this.setLocationRelativeTo(null);

        }

        public TelaInicialView(Pessoa usuario) {
            initComponents();
            this.setLocationRelativeTo(null);
            // Aqui você pode usar o objeto 'usuario' para personalizar a tela, mostrar o nome, etc.
        }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel1Banner = new javax.swing.JPanel();
        txtBarraPesquisa = new javax.swing.JTextField();
        labelBanner = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelConteudoTotal = new javax.swing.JPanel();
        panelCategoriasPrincipais = new javax.swing.JPanel();
        panelOpcoes = new javax.swing.JPanel();
        labelPanelOpcoes = new javax.swing.JLabel();
        panelTop5 = new javax.swing.JPanel();
        labelTop5MaisVendidos = new javax.swing.JLabel();
        panelFileira1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("frameInicial"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel1Banner.setBackground(new java.awt.Color(204, 204, 255));
        painel1Banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBarraPesquisa.setBorder(null);
        painel1Banner.add(txtBarraPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 140, 20));

        labelBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        painel1Banner.add(labelBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        getContentPane().add(painel1Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        panelConteudoTotal.setLayout(new javax.swing.BoxLayout(panelConteudoTotal, javax.swing.BoxLayout.Y_AXIS));

        panelCategoriasPrincipais.setLayout(new javax.swing.BoxLayout(panelCategoriasPrincipais, javax.swing.BoxLayout.Y_AXIS));

        labelPanelOpcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PainelTopo.png"))); // NOI18N
        panelOpcoes.add(labelPanelOpcoes);

        panelCategoriasPrincipais.add(panelOpcoes);

        labelTop5MaisVendidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Top5MaisVendidos.png"))); // NOI18N
        panelTop5.add(labelTop5MaisVendidos);

        panelCategoriasPrincipais.add(panelTop5);

        panelFileira1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));
        panelCategoriasPrincipais.add(panelFileira1);

        panelConteudoTotal.add(panelCategoriasPrincipais);

        jScrollPane1.setViewportView(panelConteudoTotal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    // Metodo para criação de cards de livro
    private javax.swing.JPanel criarCardLivroDinamico(String titulo, double preco) {
        // 1. Instancia o painel do Card
        javax.swing.JPanel card = new javax.swing.JPanel();
        card.setLayout(new javax.swing.BoxLayout(card, javax.swing.BoxLayout.Y_AXIS));
        card.setBackground(java.awt.Color.WHITE);
        card.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // 2. Cria a Capa (JLabel) com o tamanho fixo padrão
        javax.swing.JLabel lblCapa = new javax.swing.JLabel();
        lblCapa.setPreferredSize(new java.awt.Dimension(120, 180));
        lblCapa.setMaximumSize(new java.awt.Dimension(120, 180));
        lblCapa.setMinimumSize(new java.awt.Dimension(120, 180));
        lblCapa.setAlignmentX(0.5F);

        lblCapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capaLivro.png")));

        // Aplica o truque de escrever o título centralizado dentro da capa padrão
        lblCapa.setText("<html><body style='width: 90px; text-align: center; margin: 0 auto;'>" 
             + "<span style='color: #FFFFFF; font-family: Arial; font-size: 13px; font-weight: bold;"
             + "text-shadow: 1px 1px 3px rgba(0,0,0,0.8);'>" 
             + titulo 
             + "</span>" 
             + "</body></html>");
        lblCapa.setHorizontalTextPosition(javax.swing.JLabel.CENTER);
        lblCapa.setVerticalTextPosition(javax.swing.JLabel.CENTER);
        lblCapa.setAlignmentX(0.5F);

        // 3. Cria a Label do Preço embaixo
        javax.swing.JLabel lblPreco = new javax.swing.JLabel("R$ " + String.format("%.2f", preco));
        lblPreco.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
        lblPreco.setAlignmentX(0.5F);
        lblPreco.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));

        // 4. Cria o Botão do Carrinho
        javax.swing.JButton btnCarrinho = new javax.swing.JButton("+ Carrinho");
        btnCarrinho.setAlignmentX(0.5F);

        // Configura o evento do botão do carrinho (Exemplo rápido)
        btnCarrinho.addActionListener(e -> {
            System.out.println("Livro adicionado: " + titulo);
            // Aqui futuramente vai a lógica de injetar no carrinho da equipe de vocês
        });

        // 5. Junta todo mundo dentro do painel do Card
        card.add(lblCapa);
        card.add(lblPreco);
        card.add(card.add(btnCarrinho));

        return card;
    }

    /*public void popularFileiraNoBanco(javax.swing.JPanel painelFileira, String categoria, int limite) {
        // Limpa a fileira para não duplicar os livros caso o método seja chamado duas vezes
        painelFileira.removeAll();

        // Query dinâmica usando interrogações (?) para evitar SQL Injection
        String sql = "SELECT titulo, preco FROM livros WHERE categoria = ? LIMIT ?";

        try (java.sql.Connection conn = ConexaoBanco.getConexao(); java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

            // Define os parâmetros da busca com base no que foi passado no método
            stmt.setString(1, categoria);
            stmt.setInt(2, limite);

            try (java.sql.ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    String titulo = rs.getString("titulo");
                    double preco = rs.getDouble("preco");

                    // Fabrica o card completo usando nossa função anterior
                    javax.swing.JPanel novoCard = criarCardLivroDinamico(titulo, preco);

                    // Adiciona o card criado direto dentro da fileira do NetBeans!
                    painelFileira.add(novoCard);
                }
            }

            // COMANDO CRÍTICO: Avisa o Swing para redesenhar a tela com os novos componentes
            painelFileira.revalidate();
            painelFileira.repaint();

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar fileira: " + e.getMessage());
        }
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialView().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBanner;
    private javax.swing.JLabel labelPanelOpcoes;
    private javax.swing.JLabel labelTop5MaisVendidos;
    private javax.swing.JPanel painel1Banner;
    private javax.swing.JPanel panelCategoriasPrincipais;
    private javax.swing.JPanel panelConteudoTotal;
    private javax.swing.JPanel panelFileira1;
    private javax.swing.JPanel panelOpcoes;
    private javax.swing.JPanel panelTop5;
    private javax.swing.JTextField txtBarraPesquisa;
    // End of variables declaration//GEN-END:variables

}
