/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.livraria.view;

import com.mycompany.livraria.dao.PessoaDao;
import com.mycompany.livraria.model.Pessoa;
import com.mycompany.livraria.conexao.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Gnunes
 */
public class TelaInicialView extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialView
     */
    public TelaInicialView() {
        initComponents();
        this.setLocationRelativeTo(null);
        cardAddFileira(panelTop5, "Tecnologia", 10);

    }

    public TelaInicialView(Pessoa usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        // Aqui você pode usar o objeto 'usuario' para personalizar a tela, mostrar o nome, etc.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel1Banner = new javax.swing.JPanel();
        txtBarraPesquisa = new javax.swing.JTextField();
        labelBanner = new javax.swing.JLabel();
        panelOpcoes = new javax.swing.JPanel();
        buttonOKLogar = new javax.swing.JButton();
        buttonOKLogar1 = new javax.swing.JButton();
        buttonOKLogar2 = new javax.swing.JButton();
        panelLogoTop5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelLogoTop6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelTop5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelNovidades = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("frameInicial"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel1Banner.setBackground(new java.awt.Color(204, 204, 255));
        painel1Banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBarraPesquisa.setBorder(null);
        painel1Banner.add(txtBarraPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 140, 20));

        labelBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        painel1Banner.add(labelBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        getContentPane().add(painel1Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        panelOpcoes.setBackground(new java.awt.Color(51, 51, 51));
        panelOpcoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 200, 5));

        buttonOKLogar.setBackground(new java.awt.Color(204, 204, 204));
        buttonOKLogar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonOKLogar.setText("Entrar");
        buttonOKLogar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonOKLogar.setOpaque(true);
        buttonOKLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKLogarActionPerformed(evt);
            }
        });
        panelOpcoes.add(buttonOKLogar);

        buttonOKLogar1.setBackground(new java.awt.Color(204, 204, 204));
        buttonOKLogar1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonOKLogar1.setText("Entrar");
        buttonOKLogar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonOKLogar1.setOpaque(true);
        buttonOKLogar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKLogar1ActionPerformed(evt);
            }
        });
        panelOpcoes.add(buttonOKLogar1);

        buttonOKLogar2.setBackground(new java.awt.Color(204, 204, 204));
        buttonOKLogar2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonOKLogar2.setText("Entrar");
        buttonOKLogar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonOKLogar2.setOpaque(true);
        buttonOKLogar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKLogar2ActionPerformed(evt);
            }
        });
        panelOpcoes.add(buttonOKLogar2);

        getContentPane().add(panelOpcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 800, 30));

        panelLogoTop5.setBackground(new java.awt.Color(0, 102, 153));
        panelLogoTop5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOVIDADES");
        panelLogoTop5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 150, -1));

        getContentPane().add(panelLogoTop5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 800, 30));

        panelLogoTop6.setBackground(new java.awt.Color(0, 102, 153));
        panelLogoTop6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOP 10 LIVROS MAIS VENDIDOS");
        panelLogoTop6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 330, -1));

        getContentPane().add(panelLogoTop6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 800, 30));

        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        panelTop5.setBackground(new java.awt.Color(118, 158, 203));
        panelTop5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));
        jScrollPane1.setViewportView(panelTop5);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 800, 200));

        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        panelNovidades.setBackground(new java.awt.Color(118, 158, 203));
        panelNovidades.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));
        jScrollPane2.setViewportView(panelNovidades);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 800, 200));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 800, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOKLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKLogarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOKLogarActionPerformed

    private void buttonOKLogar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKLogar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOKLogar1ActionPerformed

    private void buttonOKLogar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKLogar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOKLogar2ActionPerformed

    // Metodo para criação de cards de livro
    private javax.swing.JPanel cardLivro(String titulo, double preco) {

        javax.swing.JPanel card = new javax.swing.JPanel();
        card.setLayout(new javax.swing.BoxLayout(card, javax.swing.BoxLayout.Y_AXIS));
        card.setOpaque(false);
        card.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 4, 4, 5));

        // Criação da Label da Capa
        javax.swing.JLabel lblCapa = new javax.swing.JLabel();

        // --- NOVO TAMANHO ATUALIZADO: 80x120 ---
        lblCapa.setPreferredSize(new java.awt.Dimension(80, 120));
        lblCapa.setMaximumSize(new java.awt.Dimension(80, 120));
        lblCapa.setMinimumSize(new java.awt.Dimension(80, 120));
        lblCapa.setAlignmentX(0.5F);

        // Carrega a imagem cinza padrão do projeto
        lblCapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capaLivro.png")));

        // Ajustado o HTML para caber perfeitamente na largura de 80px (65px de área de texto e fonte 10px)
        lblCapa.setText("<html><body style='width: 65px; text-align: center; margin: 0 auto;'>"
                + "<span style='color: #000000; font-family: Arial; font-size: 9px; font-weight: bold;"
                + "text-shadow: 1px 1px 3px rgba(0,0,0,0.8);'>"
                + titulo
                + "</span>"
                + "</body></html>");

        lblCapa.setHorizontalTextPosition(javax.swing.JLabel.CENTER);
        lblCapa.setVerticalTextPosition(javax.swing.JLabel.CENTER);
        lblCapa.setAlignmentX(0.5F);

        // Cria a Label do Preço embaixo
        javax.swing.JLabel lblPreco = new javax.swing.JLabel("R$ " + String.format("%.2f", preco));
        lblPreco.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 10));
        lblPreco.setAlignmentX(0.5F);
        lblPreco.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        

        // Cria o Botão do Carrinho
        javax.swing.JButton btnCarrinho = new javax.swing.JButton("+ Carrinho");
        java.awt.Dimension tamanhoBotao = new java.awt.Dimension(90, 15);
        btnCarrinho.setPreferredSize(tamanhoBotao);
        btnCarrinho.setMaximumSize(tamanhoBotao);
        btnCarrinho.setMinimumSize(tamanhoBotao);
        btnCarrinho.setAlignmentX(0.5F);

        // Evento do botão do carrinho 
        btnCarrinho.addActionListener(e -> {
            System.out.println("Livro adicionado: " + titulo);
            // Aqui futuramente vai a lógica de injetar no carrinho 
        });

        // Junta os componentes dentro do painel do Card
        card.add(lblCapa);
        card.add(lblPreco);
        card.add(btnCarrinho); // Correção aplicada aqui (sem o add duplicado)

        return card;

    }

    // Função para criar os banners de categoria
    public void cardAddFileira(javax.swing.JPanel painelFileira, String categoria, int limite) {

        painelFileira.removeAll();

        String sql = "SELECT nome, preco FROM Livro WHERE categoria = ? LIMIT ?";

        try (java.sql.Connection conn = ConnectionFactory.getConnection(); java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, categoria);
            stmt.setInt(2, limite);

            try (java.sql.ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    String titulo = rs.getString("nome");
                    double preco = rs.getDouble("preco");

                    javax.swing.JPanel novoCard = cardLivro(titulo, preco);

                    painelFileira.add(novoCard);
                }
            }

            painelFileira.revalidate();
            painelFileira.repaint();

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar fileira: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialView().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOKLogar;
    private javax.swing.JButton buttonOKLogar1;
    private javax.swing.JButton buttonOKLogar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBanner;
    private javax.swing.JPanel painel1Banner;
    private javax.swing.JPanel panelLogoTop5;
    private javax.swing.JPanel panelLogoTop6;
    private javax.swing.JPanel panelNovidades;
    private javax.swing.JPanel panelOpcoes;
    private javax.swing.JPanel panelTop5;
    private javax.swing.JTextField txtBarraPesquisa;
    // End of variables declaration//GEN-END:variables

}
