/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.livraria.view;

import com.mycompany.livraria.dao.CarrinhoDao;
import com.mycompany.livraria.model.Carrinho;

/**
 *
 * @author Gnunes
 */
public class TelaCarrinhoView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCarrinhoView.class.getName());

    /**
     * Creates new form TelaCarrinhoView
     */
    public TelaCarrinhoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buttonComprar = new javax.swing.JButton();
        labelPreco = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCarrinho = new javax.swing.JTable();

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carrinho");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonComprar.setBackground(new java.awt.Color(204, 204, 204));
        buttonComprar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonComprar.setText("Comprar");
        buttonComprar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonComprar.setOpaque(true);
        buttonComprar.addActionListener(this::buttonComprarActionPerformed);
        jPanel1.add(buttonComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 110, -1));

        labelPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelPreco.setOpaque(true);
        jPanel1.add(labelPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 300, 45));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        tableCarrinho.setBackground(new java.awt.Color(204, 204, 204));
        tableCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Qtde", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCarrinho);
        if (tableCarrinho.getColumnModel().getColumnCount() > 0) {
            tableCarrinho.getColumnModel().getColumn(1).setMinWidth(40);
            tableCarrinho.getColumnModel().getColumn(1).setMaxWidth(50);
            tableCarrinho.getColumnModel().getColumn(2).setMinWidth(90);
            tableCarrinho.getColumnModel().getColumn(2).setMaxWidth(95);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonComprarActionPerformed

        
        int idUsuarioLogado = 1;

        
        CarrinhoDao dao = new CarrinhoDao();
        Carrinho carrinho = dao.restaurarCarrinho(idUsuarioLogado);

        try {
           
            java.util.List<ItemCarrinho> listaDeItens = carrinho.getItens();

            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tableCarrinho.getModel();
            modelo.setNumRows(0);

            for (ItemCarrinho item : listaDeItens) {

                double subtotal = item.getPreco() * item.getQuantidade();

                modelo.addRow(new Object[]{
                    item.getTitulo(), 
                    item.getQuantidade(), 
                    String.format("R$ %.2f", subtotal) 
                });
            }

           
     
          labelPreco.setText(String.format("Total: R$ %.2f", carrinho.calcularTotal()));
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar os itens do carrinho: " + e.getMessage());
        }
    }//GEN-LAST:event_buttonComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCarrinhoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonComprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JTable tableCarrinho;
    // End of variables declaration//GEN-END:variables
}
